import Head from "next/head";
import { db } from "@/db/db";
import { account } from "@/db/schema";
import { eq } from "drizzle-orm";
import { useEffect, useState } from "react";
import * as jwt from "jose";
import * as crypto from "crypto";
import { InferGetServerSidePropsType } from "next";

export const getServerSideProps = (async (args: any) => {  
    let cookie = args.req.cookies['token']
    // Get account information to determine if there is an owner account.
    if (!cookie) {
        return {
            // Ternary operator for that determination
            props: {sessionStatus: false}
        }
    } else {
        console.log(args.req.cookies['token'])
        // @ts-ignore
        let token_info = await (await jwt.jwtVerify(cookie, crypto.createSecretKey(process.env.JWT_Secret, 'utf-8')));
        let email = token_info.payload?.email;
        // @ts-ignore
        let account_info = await db.select().from(account).where(eq(account.email, email))
        if (account_info.length == 0) {
            return {
                // Ternary operator for that determination
                props: {sessionStatus: false}
            }
        }
        return {
            // Ternary operator for that determination
            props: {sessionStatus: true, account: account_info[0]}
        }
    }
})

export default function Home(props: InferGetServerSidePropsType<typeof getServerSideProps>) {
    // Set account info
    useEffect(() => {
        if (!props.sessionStatus)  {
            window.location.href = '/'
        }
    })
    let account_info = props.account
    return(
        <>
            <Head>
                <title>Horizon Labs</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* @ts-ignore */}
            <h2>Hello, {account_info.name}!</h2>
            {/* @ts-ignore */}
            <h3>Email: {account_info.email}</h3>
            {/* @ts-ignore */}
            <h3>User ID: {account_info.id}</h3>
            {/* @ts-ignore */}
            <h3>User role: {account_info.role}</h3>
        </>
    )
}