import Head from "next/head";
import { db } from "@/db/db";
import { account } from "@/db/schema";
import { eq } from "drizzle-orm";
import { useEffect, useState } from "react";
import { Link } from "@mui/joy";

export default function Home() {
    // State flags
    const [account_info, setAccountInfo] = useState(null)

    // Am using messy approach because it was torture to get cookies to work for some reason 😭
    useEffect(() => {
        fetch('/api/session/life').then(async (res) => {
            let data = await res.json()
            if (data.coreStatus == 'NOT_ALLOWED') {
                window.location.href = '/login'
            } else {     
                setAccountInfo(data.account)
            }
        })
    }, [])
    if (account_info == null) {
        return (
            <>
                <Head>
                    <title>Horizon Labs</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <h1>Loading...</h1>
            </>
        )
    }
    return(
        <>
            <Head>
                <title>Horizon Labs</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* @ts-ignore */}
            <h2>Hello, {account_info.name}!</h2>
            {/* @ts-ignore */}
            <h3>Email: {account_info.email}</h3>
            {/* @ts-ignore */}
            <h3>User ID: {account_info.id}</h3>
            {/* @ts-ignore */}
            <h3>User role: {account_info.role}</h3>
        </>
    )
}