import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Horizon Labs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.index}>
        <div className={styles.login_background}>
        </div>
        <div className={styles.login_form}>
          <h2>Login to Horizon Labs</h2>
        </div>
      </main>
    </>
  );
}
